color:
  red: "#FF0000"
  blue: "#0000FF"
  green: "#00FF00"
  yellow: "#FFFF00"
  white: "#FFFFFF"
  black: "#000000"
  orange: "#FFA500"

features:
  # Line example - draw a flight path
  - type: line
    coordinates:
      - [116.38, 39.89]
      - [116.40, 39.90]
      - [116.42, 39.91]
      - [116.44, 39.92]
    color: orange
  
  # Area example - draw a restricted zone
  - type: area
    coordinates:
      - [116.39, 39.90]
      - [116.41, 39.90]
      - [116.41, 39.92]
      - [116.39, 39.92]
    fill: blue
    color: red
  
  # Text example - label the area
  - type: text
    coordinates:
      - [116.40, 39.91]
    text: "Test Area"
    size: 14
    color: yellow
